global proc string GFGReDeploy (string $type)
 {
	string $gfgOptsDest = "C:/Program Files/Autodesk/Maya2014/scripts/others/GFGOpts.mel";
	string $gfgOptsSrc = "D:/GitHub/GFGFileFormat/Soruce/Autodesk Maya/GFGOpts.mel";
	
	string $gfgReDeployDest = "C:/Program Files/Autodesk/Maya2014/scripts/others/GFGReDeploy.mel";
	string $gfgReDeploySrc = "D:/GitHub/GFGFileFormat/Soruce/Autodesk Maya/GFGReDeploy.mel";
	
	string $gfgErrWindowDest = "C:/Program Files/Autodesk/Maya2014/scripts/others/GFGErrorWindow.mel";
	string $gfgErrWindowSrc = "D:/GitHub/GFGFileFormat/Soruce/Autodesk Maya/GFGErrorWindow.mel";

	sysFile -copy $gfgOptsDest $gfgOptsSrc;
	sysFile -copy $gfgErrWindowDest $gfgErrWindowSrc;
	sysFile -copy $gfgReDeployDest $gfgReDeploySrc;
	source "GFGOpts.mel";
	source "GFGErrorWindow.mel";
	source "GFGReDeploy.mel";
 
	if($type == "debug")
	{
		//DEBUG
		string $destMLL = "C:/Program Files/Autodesk/Maya2014/bin/plug-ins/GFGMaya.mll";
		string $srcMLL = "D:/GitHub/GFGFileFormat/Bin64/Windows/Debug/GFGMaya.mll";

		string $destPDB = "C:/Program Files/Autodesk/Maya2014/bin/plug-ins/GFGMaya.pdb";
		string $srcPDB = "D:/GitHub/GFGFileFormat/Bin64/Windows/Debug/GFGMaya.pdb";
		
		unloadPlugin "GFGMaya.mll";
		sysFile -copy $destMLL $srcMLL;
		sysFile -copy $destPDB $srcPDB;
		loadPlugin "GFGMaya.mll";
	}
	else if($type == "release")
	{
		//RELEASE
		string $destMLL = "C:/Program Files/Autodesk/Maya2014/bin/plug-ins/GFGMaya.mll";
		string $srcMLL = "D:/GitHub/GFGFileFormat/Bin64/Windows/Release/GFGMaya.mll";

		unloadPlugin "GFGMaya.mll";
		sysFile -copy $destMLL $srcMLL;
		loadPlugin "GFGMaya.mll";
	}
	else
	{
		return "ERROR: Type is not debug or release";
	}
	
	return "OK";
}